/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.16.26
 * Mon Mar 24 14:14:24 2014
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1

/*
 * Machine selection
 */
#undef CONFIG_MIPS_MTX1
#undef CONFIG_MIPS_BOSPORUS
#undef CONFIG_MIPS_PB1000
#undef CONFIG_MIPS_PB1100
#undef CONFIG_MIPS_PB1500
#undef CONFIG_MIPS_PB1550
#undef CONFIG_MIPS_PB1200
#undef CONFIG_MIPS_DB1000
#undef CONFIG_MIPS_DB1100
#undef CONFIG_MIPS_DB1500
#undef CONFIG_MIPS_DB1550
#undef CONFIG_MIPS_DB1200
#undef CONFIG_MIPS_MIRAGE
#undef CONFIG_MIPS_COBALT
#undef CONFIG_MACH_DECSTATION
#undef CONFIG_MIPS_EV64120
#undef CONFIG_MIPS_EV96100
#undef CONFIG_MIPS_IVR
#undef CONFIG_MIPS_ITE8172
#undef CONFIG_MACH_JAZZ
#undef CONFIG_LASAT
#undef CONFIG_MIPS_ATLAS
#undef CONFIG_MIPS_MALTA
#undef CONFIG_MIPS_SEAD
#undef CONFIG_MIPS_SIM
#undef CONFIG_MOMENCO_JAGUAR_ATX
#undef CONFIG_MOMENCO_OCELOT
#undef CONFIG_MOMENCO_OCELOT_3
#undef CONFIG_MOMENCO_OCELOT_C
#undef CONFIG_MOMENCO_OCELOT_G
#undef CONFIG_MIPS_XXS1500
#undef CONFIG_PNX8550_V2PCI
#undef CONFIG_PNX8550_JBS
#undef CONFIG_DDB5074
#undef CONFIG_DDB5476
#undef CONFIG_DDB5477
#undef CONFIG_MACH_VR41XX
#undef CONFIG_PMC_YOSEMITE
#undef CONFIG_QEMU
#undef CONFIG_SGI_IP22
#undef CONFIG_SGI_IP27
#undef CONFIG_SGI_IP32
#undef CONFIG_SIBYTE_BIGSUR
#undef CONFIG_SIBYTE_SWARM
#undef CONFIG_SIBYTE_SENTOSA
#undef CONFIG_SIBYTE_RHONE
#undef CONFIG_SIBYTE_CARMEL
#undef CONFIG_SIBYTE_PTSWARM
#undef CONFIG_SIBYTE_LITTLESUR
#undef CONFIG_SIBYTE_CRHINE
#undef CONFIG_SIBYTE_CRHONE
#undef CONFIG_SNI_RM200_PCI
#undef CONFIG_TOSHIBA_JMR3927
#undef CONFIG_TOSHIBA_RBTX4927
#undef CONFIG_TOSHIBA_RBTX4938
#undef CONFIG_CAVIUM_OCTEON_SIMULATOR
#define CONFIG_CAVIUM_OCTEON_REFERENCE_BOARD 1
#define CONFIG_CAVIUM_OCTEON_SPECIFIC_OPTIONS 1
#define CONFIG_CAVIUM_OCTEON_BOOTBUS_COMPACT_FLASH 1
#define CONFIG_CAVIUM_OCTEON_HW_FIX_UNALIGNED 1
#define CONFIG_FAST_ACCESS_TO_THREAD_POINTER 1
#define CONFIG_REPLACE_EMULATED_ACCESS_TO_THREAD_POINTER 1
#define CONFIG_CAVIUM_OCTEON_CVMSEG_SIZE 2
#define CONFIG_CAVIUM_OCTEON_LOCK_L2 1
#define CONFIG_CAVIUM_OCTEON_LOCK_L2_TLB 1
#define CONFIG_CAVIUM_OCTEON_LOCK_L2_EXCEPTION 1
#define CONFIG_CAVIUM_OCTEON_LOCK_L2_LOW_LEVEL_INTERRUPT 1
#define CONFIG_CAVIUM_OCTEON_LOCK_L2_INTERRUPT 1
#define CONFIG_CAVIUM_OCTEON_LOCK_L2_MEMCPY 1
#define CONFIG_CAVIUM_OCTEON_USER_IO 1
#define CONFIG_CAVIUM_OCTEON_USER_MEM 1
#define CONFIG_CAVIUM_RESERVE32 0
#define CONFIG_CAVIUM_OCTEON_NUM_PACKET_BUFFERS 0
#define CONFIG_ARCH_SPARSEMEM_ENABLE 1
#undef CONFIG_CAVIUM_OCTEON_POW_ONLY_ETHERNET
#undef CONFIG_CAVIUM_OCTEON_IPSEC
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_ARCH_MAY_HAVE_PC_FDC 1
#define CONFIG_OWN_DMA 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_CPU_BIG_ENDIAN 1
#undef CONFIG_CPU_LITTLE_ENDIAN
#define CONFIG_SYS_SUPPORTS_BIG_ENDIAN 1
#define CONFIG_IRQ_CPU_OCTEON 1
#define CONFIG_SWAP_IO_SPACE 1
#define CONFIG_MIPS_L1_CACHE_SHIFT 7

/*
 * CPU selection
 */
#undef CONFIG_CPU_MIPS32_R1
#undef CONFIG_CPU_MIPS32_R2
#undef CONFIG_CPU_MIPS64_R1
#undef CONFIG_CPU_MIPS64_R2
#undef CONFIG_CPU_R3000
#undef CONFIG_CPU_TX39XX
#undef CONFIG_CPU_VR41XX
#undef CONFIG_CPU_R4300
#undef CONFIG_CPU_R4X00
#undef CONFIG_CPU_TX49XX
#undef CONFIG_CPU_R5000
#undef CONFIG_CPU_R5432
#undef CONFIG_CPU_R6000
#undef CONFIG_CPU_NEVADA
#undef CONFIG_CPU_R8000
#undef CONFIG_CPU_R10000
#undef CONFIG_CPU_RM7000
#undef CONFIG_CPU_RM9000
#undef CONFIG_CPU_SB1
#define CONFIG_CPU_CAVIUM_OCTEON 1
#define CONFIG_CPU_MIPSR2 1
#define CONFIG_SYS_SUPPORTS_64BIT_KERNEL 1
#define CONFIG_CPU_SUPPORTS_64BIT_KERNEL 1

/*
 * Kernel type
 */
#undef CONFIG_32BIT
#define CONFIG_64BIT 1
#define CONFIG_PAGE_SIZE_4KB 1
#undef CONFIG_PAGE_SIZE_8KB
#undef CONFIG_PAGE_SIZE_16KB
#undef CONFIG_PAGE_SIZE_64KB
#define CONFIG_CPU_HAS_PREFETCH 1
#undef CONFIG_MIPS_MT
#define CONFIG_CPU_HAS_LLSC 1
#define CONFIG_CPU_HAS_SYNC 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_ARCH_FLATMEM_ENABLE 1
#define CONFIG_SELECT_MEMORY_MODEL 1
#undef CONFIG_FLATMEM_MANUAL
#undef CONFIG_DISCONTIGMEM_MANUAL
#define CONFIG_SPARSEMEM_MANUAL 1
#define CONFIG_SPARSEMEM 1
#define CONFIG_HAVE_MEMORY_PRESENT 1
#define CONFIG_SPARSEMEM_STATIC 1
#undef CONFIG_MEMORY_HOTPLUG
#define CONFIG_SPLIT_PTLOCK_CPUS 4
#define CONFIG_MIGRATION 1
#define CONFIG_SMP 1
#define CONFIG_NR_CPUS 2
#define CONFIG_PREEMPT_NONE 1
#undef CONFIG_PREEMPT_VOLUNTARY
#undef CONFIG_PREEMPT
#undef CONFIG_PREEMPT_BKL

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_LOCK_KERNEL 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION "-Cavium-Octeon"
#undef CONFIG_LOCALVERSION_AUTO
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#undef CONFIG_BSD_PROCESS_ACCT_V3
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#undef CONFIG_IKCONFIG
#undef CONFIG_CPUSETS
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_HOTPLUG 1
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_ELF_CORE 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#define CONFIG_SLAB 1
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0
#undef CONFIG_SLOB
#define CONFIG_OBSOLETE_INTERMODULE 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#undef CONFIG_MODVERSIONS
#undef CONFIG_MODULE_SRCVERSION_ALL
#undef CONFIG_KMOD
#define CONFIG_STOP_MACHINE 1

/*
 * Block layer
 */

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#undef CONFIG_IOSCHED_AS
#undef CONFIG_IOSCHED_DEADLINE
#define CONFIG_IOSCHED_CFQ 1
#undef CONFIG_DEFAULT_AS
#undef CONFIG_DEFAULT_DEADLINE
#define CONFIG_DEFAULT_CFQ 1
#undef CONFIG_DEFAULT_NOOP
#define CONFIG_DEFAULT_IOSCHED "cfq"

/*
 * Bus options (PCI, PCMCIA, EISA, ISA, TC)
 */
#define CONFIG_HW_HAS_PCI 1
#define CONFIG_PCI 1
#define CONFIG_PCI_LEGACY_PROC 1
#define CONFIG_ISA 1
#define CONFIG_MMU 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD 1
#undef CONFIG_PCMCIA_DEBUG
#undef CONFIG_PCMCIA
#define CONFIG_CARDBUS 1

/*
 * PC-card bridges
 */
#define CONFIG_YENTA 1
#define CONFIG_YENTA_O2 1
#define CONFIG_YENTA_RICOH 1
#define CONFIG_YENTA_TI 1
#undef CONFIG_YENTA_ENE_TUNE
#define CONFIG_YENTA_TOSHIBA 1
#define CONFIG_PCMCIA_PROBE 1
#define CONFIG_PCCARD_NONSTATIC 1

/*
 * PCI Hotplug Support
 */
#undef CONFIG_HOTPLUG_PCI

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC 1
#define CONFIG_BUILD_ELF64 1
#define CONFIG_MIPS32_COMPAT 1
#define CONFIG_COMPAT 1
#define CONFIG_MIPS32_O32 1
#define CONFIG_MIPS32_N32 1
#define CONFIG_BINFMT_ELF32 1

/*
 * Networking
 */
#define CONFIG_NK_IPV6_ADDON 1
#define CONFIG_NET 1

/*
 * Networking options
 */
#undef CONFIG_NETDEBUG
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER 1
#define CONFIG_NET_KEY 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_ASK_IP_FIB_HASH 1
#undef CONFIG_IP_FIB_TRIE
#define CONFIG_IP_FIB_HASH 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_MULTIPATH 1
#undef CONFIG_IP_ROUTE_MULTIPATH_CACHED
#undef CONFIG_IP_ROUTE_VERBOSE
#undef CONFIG_IP_PNP
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH 1
#define CONFIG_INET_ESP 1
#define CONFIG_INET_IPCOMP 1
#define CONFIG_INET_TUNNEL 1
#undef CONFIG_INET_DIAG
#undef CONFIG_TCP_CONG_ADVANCED
#define CONFIG_TCP_CONG_BIC 1

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#define CONFIG_IPV6 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH 1
#define CONFIG_INET6_ESP 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL 1
#define CONFIG_IPV6_TUNNEL 1
#define CONFIG_OCTEON_NATIVE_IPSEC 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#undef CONFIG_BRIDGE_NETFILTER

/*
 * Core Netfilter Configuration
 */
#define CONFIG_NETFILTER_NETLINK 1
#undef CONFIG_NETFILTER_NETLINK_QUEUE
#undef CONFIG_NETFILTER_NETLINK_LOG
#define CONFIG_NETFILTER_XTABLES 1
#undef CONFIG_NETFILTER_XT_TARGET_CLASSIFY
#undef CONFIG_NETFILTER_XT_TARGET_CONNMARK
#undef CONFIG_NETFILTER_XT_TARGET_MARK
#undef CONFIG_NETFILTER_XT_TARGET_NFQUEUE
#undef CONFIG_NETFILTER_XT_TARGET_NOTRACK
#undef CONFIG_NETFILTER_XT_MATCH_COMMENT
#undef CONFIG_NETFILTER_XT_MATCH_CONNBYTES
#undef CONFIG_NETFILTER_XT_MATCH_CONNMARK
#undef CONFIG_NETFILTER_XT_MATCH_CONNTRACK
#undef CONFIG_NETFILTER_XT_MATCH_DCCP
#undef CONFIG_NETFILTER_XT_MATCH_HELPER
#undef CONFIG_NETFILTER_XT_MATCH_LENGTH
#define CONFIG_NETFILTER_XT_MATCH_LIMIT 1
#define CONFIG_NETFILTER_XT_MATCH_MAC 1
#undef CONFIG_NETFILTER_XT_MATCH_MARK
#undef CONFIG_NETFILTER_XT_MATCH_PKTTYPE
#undef CONFIG_NETFILTER_XT_MATCH_REALM
#undef CONFIG_NETFILTER_XT_MATCH_SCTP
#define CONFIG_NETFILTER_XT_MATCH_STATE 1
#define CONFIG_NETFILTER_XT_MATCH_STRING 1
#define CONFIG_NETFILTER_XT_MATCH_TCPMSS 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#define CONFIG_IP_NF_CONNTRACK_EVENTS 1
#define CONFIG_IP_NF_CONNTRACK_NETLINK 1
#undef CONFIG_IP_NF_CT_PROTO_SCTP
#define CONFIG_IP_NF_FTP 1
#undef CONFIG_IP_NF_IRC
#define CONFIG_IP_NF_NETBIOS_NS 1
#define CONFIG_IP_NF_TFTP 1
#undef CONFIG_IP_NF_AMANDA
#define CONFIG_IP_NF_PPTP 1
#define CONFIG_IP_NF_QUEUE 1
#define CONFIG_IP_NF_IPTABLES 1
#define CONFIG_IP_NF_MATCH_IPRANGE 1
#define CONFIG_IP_NF_MATCH_LAYER7 1
#undef CONFIG_IP_NF_MATCH_LAYER7_DEBUG
#define CONFIG_IP_NF_MATCH_MULTIPORT 1
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#undef CONFIG_IP_NF_MATCH_ECN
#undef CONFIG_IP_NF_MATCH_DSCP
#define CONFIG_IP_NF_MATCH_AH_ESP 1
#define CONFIG_IP_NF_MATCH_TTL 1
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_MATCH_POLICY 1
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#define CONFIG_IP_NF_TARGET_LOG 1
#undef CONFIG_IP_NF_TARGET_ULOG
#define CONFIG_IP_NF_TARGET_TCPMSS 1
#define CONFIG_IP_NF_NAT 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE 1
#define CONFIG_IP_NF_TARGET_REDIRECT 1
#undef CONFIG_IP_NF_TARGET_NETMAP
#undef CONFIG_IP_NF_TARGET_SAME
#define CONFIG_IP_NF_NAT_SNMP_BASIC 1
#define CONFIG_IP_NF_NAT_FTP 1
#define CONFIG_IP_NF_NAT_TFTP 1
#define CONFIG_IP_NF_NAT_PPTP 1
#undef CONFIG_IP_NF_MANGLE
#define CONFIG_IP_NF_RAW 1
#define CONFIG_IP_NF_ARPTABLES 1
#define CONFIG_IP_NF_ARPFILTER 1
#define CONFIG_IP_NF_ARP_MANGLE 1
#define CONFIG_IP_NF_ESP 1
#define CONFIG_IP_NF_TARGET_TRIGGER 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP6_NF_QUEUE 1
#define CONFIG_IP6_NF_IPTABLES 1
#define CONFIG_IP6_NF_MATCH_RT 1
#define CONFIG_IP6_NF_MATCH_OPTS 1
#define CONFIG_IP6_NF_MATCH_FRAG 1
#define CONFIG_IP6_NF_MATCH_HL 1
#define CONFIG_IP6_NF_MATCH_MULTIPORT 1
#define CONFIG_IP6_NF_MATCH_OWNER 1
#define CONFIG_IP6_NF_MATCH_IPV6HEADER 1
#define CONFIG_IP6_NF_MATCH_AHESP 1
#define CONFIG_IP6_NF_MATCH_EUI64 1
#define CONFIG_IP6_NF_MATCH_POLICY 1
#define CONFIG_IP6_NF_FILTER 1
#define CONFIG_IP6_NF_TARGET_LOG 1
#define CONFIG_IP6_NF_TARGET_REJECT 1
#define CONFIG_IP6_NF_MANGLE 1
#define CONFIG_IP6_NF_TARGET_HL 1
#define CONFIG_IP6_NF_RAW 1

/*
 * Bridge: Netfilter Configuration
 */
#undef CONFIG_BRIDGE_NF_EBTABLES

/*
 * DCCP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_DCCP

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP

/*
 * TIPC Configuration (EXPERIMENTAL)
 */
#undef CONFIG_TIPC
#undef CONFIG_ATM
#define CONFIG_BRIDGE 1
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU

/*
 * Queueing/Scheduling
 */
#define CONFIG_NET_SCH_CBQ 1
#define CONFIG_NET_SCH_HTB 1
#define CONFIG_NET_SCH_HFSC 1
#define CONFIG_NET_SCH_PRIO 1
#define CONFIG_NET_SCH_RED 1
#define CONFIG_NET_SCH_SFQ 1
#define CONFIG_NET_SCH_TEQL 1
#define CONFIG_NET_SCH_TBF 1
#define CONFIG_NET_SCH_GRED 1
#define CONFIG_NET_SCH_DSMARK 1
#define CONFIG_NET_SCH_NETEM 1
#define CONFIG_NET_SCH_INGRESS 1

/*
 * Classification
 */
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC 1
#define CONFIG_NET_CLS_TCINDEX 1
#define CONFIG_NET_CLS_ROUTE4 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW 1
#define CONFIG_NET_CLS_U32 1
#define CONFIG_CLS_U32_PERF 1
#define CONFIG_CLS_U32_MARK 1
#define CONFIG_NET_CLS_RSVP 1
#define CONFIG_NET_CLS_RSVP6 1
#define CONFIG_NET_EMATCH 1
#define CONFIG_NET_EMATCH_STACK 32
#define CONFIG_NET_EMATCH_CMP 1
#define CONFIG_NET_EMATCH_NBYTE 1
#define CONFIG_NET_EMATCH_U32 1
#define CONFIG_NET_EMATCH_META 1
#define CONFIG_NET_EMATCH_TEXT 1
#define CONFIG_NET_CLS_ACT 1
#define CONFIG_NET_ACT_POLICE 1
#define CONFIG_NET_ACT_GACT 1
#define CONFIG_GACT_PROB 1
#define CONFIG_NET_ACT_MIRRED 1
#define CONFIG_NET_ACT_IPT 1
#define CONFIG_NET_ACT_PEDIT 1
#define CONFIG_NET_ACT_SIMP 1
#define CONFIG_NET_CLS_IND 1
#define CONFIG_NET_ESTIMATOR 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#undef CONFIG_IEEE80211

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#undef CONFIG_FW_LOADER

/*
 * Connector - unified userspace <-> kernelspace linker
 */
#undef CONFIG_CONNECTOR

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_CONCAT
#define CONFIG_MTD_PARTITIONS 1
#undef CONFIG_MTD_REDBOOT_PARTS
#define CONFIG_MTD_CMDLINE_PARTS 1

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL
#undef CONFIG_RFD_FTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#define CONFIG_MTD_JEDECPROBE 1
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_4
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#undef CONFIG_MTD_CFI_I2
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#undef CONFIG_MTD_OTP
#define CONFIG_MTD_CFI_INTELEXT 1
#define CONFIG_MTD_CFI_AMDSTD 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#undef CONFIG_MTD_CFI_STAA
#define CONFIG_MTD_CFI_UTIL 1
#undef CONFIG_MTD_RAM
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT
#undef CONFIG_MTD_OBSOLETE_CHIPS

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS
#define CONFIG_MTD_PHYSMAP 1
#define CONFIG_MTD_PHYSMAP_START 0x1f400000
#define CONFIG_MTD_PHYSMAP_LEN 0x800000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 1
#undef CONFIG_MTD_CSTM_MIPS_IXX
#undef CONFIG_MTD_PLATRAM

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_PMC551
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_MTD_BLKMTD
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#undef CONFIG_MTD_NAND

/*
 * OneNAND Flash Device Drivers
 */
#undef CONFIG_MTD_ONENAND

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */
#undef CONFIG_PNP

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#undef CONFIG_BLK_DEV_DAC960
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#undef CONFIG_BLK_DEV_NBD
#undef CONFIG_BLK_DEV_SX8
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 1
#define CONFIG_BLK_DEV_RAM_SIZE 500000
#undef CONFIG_BLK_DEV_INITRD
#undef CONFIG_CDROM_PKTCDVD
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#define CONFIG_BLK_DEV_IDECD 1
#undef CONFIG_BLK_DEV_IDETAPE
#undef CONFIG_BLK_DEV_IDEFLOPPY
#undef CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#undef CONFIG_IDE_GENERIC
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#undef CONFIG_BLK_DEV_GENERIC
#undef CONFIG_BLK_DEV_OPTI621
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef CONFIG_IDEDMA_ONLYDISK
#undef CONFIG_BLK_DEV_AEC62XX
#undef CONFIG_BLK_DEV_ALI15X3
#undef CONFIG_BLK_DEV_AMD74XX
#define CONFIG_BLK_DEV_CMD64X 1
#undef CONFIG_BLK_DEV_TRIFLEX
#undef CONFIG_BLK_DEV_CY82C693
#undef CONFIG_BLK_DEV_CS5520
#undef CONFIG_BLK_DEV_CS5530
#undef CONFIG_BLK_DEV_HPT34X
#undef CONFIG_BLK_DEV_HPT366
#undef CONFIG_BLK_DEV_SC1200
#undef CONFIG_BLK_DEV_PIIX
#undef CONFIG_BLK_DEV_IT821X
#undef CONFIG_BLK_DEV_NS87415
#undef CONFIG_BLK_DEV_PDC202XX_OLD
#undef CONFIG_BLK_DEV_PDC202XX_NEW
#undef CONFIG_BLK_DEV_SVWKS
#undef CONFIG_BLK_DEV_SIIMAGE
#undef CONFIG_BLK_DEV_SLC90E66
#undef CONFIG_BLK_DEV_TRM290
#define CONFIG_BLK_DEV_VIA82CXXX 1
#undef CONFIG_IDE_ARM
#undef CONFIG_IDE_CHIPSETS
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#undef CONFIG_RAID_ATTRS
#undef CONFIG_SCSI

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef CONFIG_CD_NO_IDESCSI

/*
 * Multi-device support (RAID and LVM)
 */
#undef CONFIG_MD

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION

/*
 * IEEE 1394 (FireWire) support
 */
#undef CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#define CONFIG_IFB 1
#undef CONFIG_DUMMY
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#define CONFIG_TUN 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * PHY device support
 */
#undef CONFIG_PHYLIB

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#undef CONFIG_HAPPYMEAL
#undef CONFIG_SUNGEM
#undef CONFIG_CASSINI
#undef CONFIG_NET_VENDOR_3COM
#undef CONFIG_NET_VENDOR_SMC
#undef CONFIG_DM9000
#undef CONFIG_NET_VENDOR_RACAL

/*
 * Tulip family network device support
 */
#undef CONFIG_NET_TULIP
#undef CONFIG_AT1700
#undef CONFIG_DEPCA
#undef CONFIG_HP100
#undef CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#undef CONFIG_PCNET32
#undef CONFIG_AMD8111_ETH
#undef CONFIG_ADAPTEC_STARFIRE
#undef CONFIG_AC3200
#undef CONFIG_APRICOT
#undef CONFIG_B44
#undef CONFIG_FORCEDETH
#undef CONFIG_CS89x0
#undef CONFIG_DGRS
#undef CONFIG_EEPRO100
#undef CONFIG_E100
#undef CONFIG_FEALNX
#undef CONFIG_NATSEMI
#undef CONFIG_NE2K_PCI
#undef CONFIG_8139CP
#undef CONFIG_8139TOO
#undef CONFIG_SIS900
#undef CONFIG_EPIC100
#undef CONFIG_SUNDANCE
#undef CONFIG_VIA_RHINE
#undef CONFIG_LAN_SAA9730

/*
 * Ethernet (1000 Mbit)
 */
#undef CONFIG_ACENIC
#undef CONFIG_DL2K
#undef CONFIG_E1000
#undef CONFIG_NS83820
#undef CONFIG_HAMACHI
#undef CONFIG_YELLOWFIN
#undef CONFIG_R8169
#undef CONFIG_SIS190
#undef CONFIG_SKGE
#undef CONFIG_SKY2
#undef CONFIG_SK98LIN
#undef CONFIG_VIA_VELOCITY
#undef CONFIG_TIGON3
#undef CONFIG_BNX2

/*
 * Ethernet (10000 Mbit)
 */
#undef CONFIG_CHELSIO_T1
#undef CONFIG_IXGB
#undef CONFIG_S2IO

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_WAVELAN

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#undef CONFIG_HERMES
#undef CONFIG_ATMEL

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#undef CONFIG_PRISM54
#undef CONFIG_HOSTAP
#define CONFIG_NET_WIRELESS 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_FDDI
#undef CONFIG_HIPPI
#define CONFIG_PPP 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC 1
#define CONFIG_PPP_SYNC_TTY 1
#define CONFIG_PPP_DEFLATE 1
#define CONFIG_PPP_BSDCOMP 1
#define CONFIG_PPP_MPPE_MPPC 1
#define CONFIG_PPPOE 1
#define CONFIG_PPPOL2TP 1
#undef CONFIG_SLIP
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#undef CONFIG_INPUT_MOUSEDEV
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#undef CONFIG_INPUT_EVDEV
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#undef CONFIG_INPUT_KEYBOARD
#undef CONFIG_INPUT_MOUSE
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#undef CONFIG_SERIO_I8042
#define CONFIG_SERIO_SERPORT 1
#undef CONFIG_SERIO_PCIPS2
#undef CONFIG_SERIO_LIBPS2
#undef CONFIG_SERIO_RAW
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#undef CONFIG_VT_CONSOLE
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#undef CONFIG_COMPUTONE
#undef CONFIG_ROCKETPORT
#undef CONFIG_CYCLADES
#undef CONFIG_DIGIEPCA
#undef CONFIG_MOXA_INTELLIO
#undef CONFIG_MOXA_SMARTIO
#undef CONFIG_ISI
#undef CONFIG_SYNCLINKMP
#undef CONFIG_SYNCLINK_GT
#define CONFIG_N_HDLC_MODULE 1
#undef CONFIG_SPECIALIX
#undef CONFIG_SX
#undef CONFIG_STALDRV

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_NR_UARTS 4
#define CONFIG_SERIAL_8250_RUNTIME_UARTS 4
#define CONFIG_SERIAL_8250_EXTENDED 1
#undef CONFIG_SERIAL_8250_MANY_PORTS
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#undef CONFIG_SERIAL_8250_RSA

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#undef CONFIG_SERIAL_JSM
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#undef CONFIG_WATCHDOG
#undef CONFIG_RTC
#undef CONFIG_GEN_RTC
#undef CONFIG_DTLK
#undef CONFIG_R3964
#undef CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_DRM
#undef CONFIG_RAW_DRIVER

/*
 * TPM devices
 */
#undef CONFIG_TCG_TPM
#undef CONFIG_TELCLOCK

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT 1
#undef CONFIG_I2C_ALGOPCF
#undef CONFIG_I2C_ALGOPCA

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ALI1535
#undef CONFIG_I2C_ALI1563
#undef CONFIG_I2C_ALI15X3
#undef CONFIG_I2C_AMD756
#undef CONFIG_I2C_AMD8111
#undef CONFIG_I2C_I801
#undef CONFIG_I2C_I810
#undef CONFIG_I2C_PIIX4
#undef CONFIG_I2C_NFORCE2
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_PROSAVAGE
#undef CONFIG_I2C_SAVAGE4
#undef CONFIG_SCx200_ACB
#undef CONFIG_I2C_SIS5595
#undef CONFIG_I2C_SIS630
#undef CONFIG_I2C_SIS96X
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_VIA
#undef CONFIG_I2C_VIAPRO
#undef CONFIG_I2C_VOODOO3
#undef CONFIG_I2C_PCA_ISA
#define CONFIG_I2C_OCTEON_TWSI 1

/*
 * Miscellaneous I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_DS1374
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCA9539
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_SENSORS_MAX6875
#undef CONFIG_RTC_X1205_I2C
#define CONFIG_RTC_RS5C372_I2C 1
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * SPI support
 */
#undef CONFIG_SPI
#undef CONFIG_SPI_MASTER

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Hardware Monitoring support
 */
#undef CONFIG_HWMON
#undef CONFIG_HWMON_VID

/*
 * Misc devices
 */

/*
 * Multimedia Capabilities Port drivers
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#undef CONFIG_FB_CFB_FILLRECT
#undef CONFIG_FB_CFB_COPYAREA
#undef CONFIG_FB_CFB_IMAGEBLIT
#undef CONFIG_FB_MACMODES
#define CONFIG_FB_MODE_HELPERS 1
#undef CONFIG_FB_TILEBLITTING
#undef CONFIG_FB_CIRRUS
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#undef CONFIG_FB_S1D13XXX
#undef CONFIG_FB_NVIDIA
#undef CONFIG_FB_RIVA
#undef CONFIG_FB_MATROX
#undef CONFIG_FB_RADEON_OLD
#undef CONFIG_FB_RADEON
#undef CONFIG_FB_ATY128
#undef CONFIG_FB_ATY
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_SMIVGX
#undef CONFIG_FB_TRIDENT
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#undef CONFIG_VGA_CONSOLE
#undef CONFIG_MDA_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FRAMEBUFFER_CONSOLE_ROTATION
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#undef CONFIG_LOGO
#undef CONFIG_BACKLIGHT_LCD_SUPPORT

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1
#undef CONFIG_USB

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support'
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * InfiniBand support
 */
#undef CONFIG_INFINIBAND

/*
 * EDAC - error detection and reporting (RAS) (EXPERIMENTAL)
 */

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#undef CONFIG_EXT2_FS_XATTR
#undef CONFIG_EXT2_FS_XIP
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#undef CONFIG_EXT3_FS_POSIX_ACL
#undef CONFIG_EXT3_FS_SECURITY
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS
#undef CONFIG_FS_POSIX_ACL
#undef CONFIG_XFS_FS
#undef CONFIG_OCFS2_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#define CONFIG_INOTIFY 1
#undef CONFIG_QUOTA
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS
#undef CONFIG_FUSE_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#undef CONFIG_ZISOFS
#undef CONFIG_UDF_FS

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#undef CONFIG_MSDOS_FS
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#define CONFIG_TMPFS 1
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1
#undef CONFIG_RELAYFS_FS
#undef CONFIG_CONFIGFS_FS

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_WRITEBUFFER 1
#undef CONFIG_JFFS2_SUMMARY
#undef CONFIG_JFFS2_COMPRESSION_OPTIONS
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#define CONFIG_CRAMFS 1
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#undef CONFIG_NFS_FS
#undef CONFIG_NFSD
#undef CONFIG_SMB_FS
#undef CONFIG_CIFS
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS
#undef CONFIG_9P_FS

/*
 * Partition Types
 */
#undef CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437 1
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#undef CONFIG_NLS_CODEPAGE_850
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#undef CONFIG_NLS_CODEPAGE_936
#undef CONFIG_NLS_CODEPAGE_950
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#define CONFIG_NLS_ISO8859_1 1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#undef CONFIG_NLS_ISO8859_15
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#undef CONFIG_NLS_UTF8

/*
 * Profiling support
 */
#undef CONFIG_PROFILING

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#define CONFIG_MAGIC_SYSRQ 1
#undef CONFIG_DEBUG_KERNEL
#define CONFIG_LOG_BUF_SHIFT 15
#undef CONFIG_CROSSCOMPILE
#define CONFIG_CMDLINE "root=/dev/mtdblock2 ro rootfstype=cramfs mtdparts=phys_mapped_flash:512k(bootloader)ro,5120k(image),25600k(FS),1024k(DB),256k(rg_factory),256k(other)"

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL 1
#undef CONFIG_CRYPTO_MD4
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#undef CONFIG_CRYPTO_SHA256
#undef CONFIG_CRYPTO_SHA512
#undef CONFIG_CRYPTO_WP512
#undef CONFIG_CRYPTO_TGR192
#define CONFIG_CRYPTO_DES 1
#undef CONFIG_CRYPTO_BLOWFISH
#undef CONFIG_CRYPTO_TWOFISH
#undef CONFIG_CRYPTO_SERPENT
#define CONFIG_CRYPTO_AES 1
#undef CONFIG_CRYPTO_CAST5
#undef CONFIG_CRYPTO_CAST6
#undef CONFIG_CRYPTO_TEA
#define CONFIG_CRYPTO_ARC4 1
#undef CONFIG_CRYPTO_KHAZAD
#undef CONFIG_CRYPTO_ANUBIS
#define CONFIG_CRYPTO_DEFLATE 1
#undef CONFIG_CRYPTO_MICHAEL_MIC
#undef CONFIG_CRYPTO_CRC32C
#undef CONFIG_CRYPTO_TEST

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#undef CONFIG_CRC16
#define CONFIG_CRC32 1
#undef CONFIG_LIBCRC32C
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
#define CONFIG_TEXTSEARCH 1
#define CONFIG_TEXTSEARCH_KMP 1
#define CONFIG_TEXTSEARCH_BM 1
#define CONFIG_TEXTSEARCH_FSM 1
